language: shell

install: true
script: true

before_deploy:
  - .travis/providers/anynines/prepare
  - cd tmp/dpl_test
  - ls -al

deploy:
  - provider: anynines

    username: dpl-test@travis-ci.org
    password:
      secure: "dopn4dUR3YruM9pZmdOPlUeAibxBZ9vcWZkG9lQo4KCXBsrqU/B1oeRy9fd9/dOewJHGlaY23gHaxFodOVwZpr6yCIzLn4uVO7r+pNlFuwZHOBlVlqI1Qoumoc8qsoGorRd0yfD5VCa4MjOvsOIEShuEIdmnSFRHf03gdDJM1Us="
    organization: dpl-test_travis-ci_org
    space: test
    app_name: dpl-test
    buildpack: ruby_buildpack
    logout: false

after_deploy:
  - cd ../..
  - .travis/providers/anynines/test || TRAVIS_TEST_RESULT=$?
  - tmp/dpl_test/cf scale dpl-test -i 0
