dist: xenial
language: rust

script:
  - true

before_deploy:
  - .travis/providers/cargo/prepare
  - cd tmp/dpl_test

deploy:
  - provider: cargo
    allow_dirty: true
    token:
      secure: "nlMiqpZRZdJ7Q66jpsIaHst/qNQS5sGQyIZrpjWUWw/mKe0Hdgxdu0FzLA46rmJK2hwE5hIw2oGtlMyy6zaAitRu3GI60fd0ABN/HOwntcyL+IrcftQe0ZqaEMW9dWoQo7I2UWNujVFYPDTrckRogN8AXrEwK0bnOPS1fuxmJ4U="

after_deploy:
  - cd ../..
  - .travis/providers/cargo/test || TRAVIS_TEST_RESULT=$?
