language: shell

script:
  - true

before_deploy:
  - .travis/providers/rubygems/prepare&
  - while ! curl -s http://localhost:9292 >/dev/null; do sleep 1; done
  - cd tmp/dpl_test_rubygems

deploy:
  - provider: rubygems
    username:
      # the string username
      secure: "XGeKKoJAMCH88Es5PvfY/+WW8KneG+fsygOyj0ov+RuJkIlcm44mES6scM8yCXPYecVX6gDPaIegz63g0VDVgM+uGN5/z9UKO2q7t39R+r7APml2CT1hq21zWcF6SsaM+kEwzuK4COy0RsLxOG0fX+wankEUes2n15UBSfasp2s="
    password:
      # the string password
      secure: "HNromDkeUbrKu+uvYt3SOQ/OCB//A2oxvlRudU1ECuh+5lyyLnXLR6vVxbAEUc7GNNNQp722lyV9Ni4y1GroIDGH7ysviA3u1cUaY8d1PHs3/xBxjgOnNcvnz4d4LUWIEhdELpacLPqe1U0H+EmfbyxV3EZ7Xo8IU7QrEMQyytw="
    gem: dpl_test
    gemspec_glob: ./dpl_*.gemspec
    host: http://localhost:9292

after_deploy:
  - cd ../.. && .travis/providers/rubygems/test || TRAVIS_TEST_RESULT=$?
