language: node_js

script:
  - true

before_deploy:
  - .travis/providers/npm/prepare
  - cd tmp/dpl_test

deploy:
  - provider: npm
    edge:
      branch: dpl-2
    on:
      branch: dpl-2

    email: dpl-test@travis-ci.org
    api_key:
      secure: "cvaSdHFNK//eo1fkI4WKMxAd9L+8kaflwbfaOACnDclt+5iqcOAZ4Rn/x9Ook4DdPg6oahiSqWDwTcnCO/K58BiJkB2jXzdFBsjDUIQfqvI2hpnFnzuUxRi0Q3Smo2NgwZezej5Q7g5zqSRRYVTHiF3eGaQPw8kKM3cE9WaGe8c="
    access: public
    skip_cleanup: true

after_deploy:
  - cd ../..
  - .travis/providers/npm/test || TRAVIS_TEST_RESULT=$?
